spring:
  datasource:
    url: jdbc:mysql://localhost:3306/school_service_db?useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

#  security:
#    user:
#      name: admin
#      password: admin

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
#    show-sql: true



